apiVersion: v1
kind: Service
metadata:
  name: qq-bot
  labels:
    app: qq-bot
spec:
  ports:
    - port: 80
      targetPort: 30001
      nodePort: 30001
  selector:
    app: qq-bot
    type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qq-bot
  labels:
    app: qq-bot
    version: v1
spec:
  selector:
    matchLabels:
      app: qq-bot
      version: v1
  template:
    metadata:
      labels:
        app: qq-bot
        version: v1
    spec:
      containers:
        - image: oneadm/qq-bot:1.0
          imagePullPolicy: Always
          name: qq-bot
          command: [ "/bin/sh", "-c", "env" ]
          envFrom:
            - configMapRef:
                name: java-configmap
            - configMapRef:
                name: qq-bot
          command: ["java", "-Dspring.profiles.active=prod", "-jar", "app.jar"]
          ports:
            - containerPort: 30001
              name: http
