server:
  port: 30001

spring:
  application:
    name: qq-bot
  datasource:
    username: ${mysql_username:root}
    password: ${mysql_password:aaa1024}
    url: ${mysql_url:jdbc:mysql://119.91.222.75:3306/qq_bot?serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=UTF-8&autoReconnect=true}
    driver-class-name: com.mysql.jdbc.Driver

qq:
  bot:
    username: ${qq_bot_username:1273854603}
    type: ${qq_bot_type:android_watch}
    password: ${qq_bot_pass:Aaa10247878=-}
    login-type: ${qq_bot_login_type:qrcode}
    deviceInfo: |
      {"display":[107,52,48,115,46,50,48,52,48,46,49,48,56,48],"product":[-25,-70,-94,-25,-79,-77,107,52,48,115],"device":[109,115,109,105],"board":[109,115,109,105,56,55,48],"brand":[88,105,97,111,77,105],"model":[82,101,100,109,105,75,52,48,115],"bootloader":[117,110,107,110,111,119,110],"fingerprint":[88,105,97,111,109,105,47,115,97,103,105,116,47,115,97,103,105,116,58,56,46,48,46,48,47,79,8

logging:
  level:
    com.jky.qqbot.mapper: debug
